from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'cmsMeta',
    'Post',
    'socialLink',
    'author',
    'Token',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'cmsMeta': {
    },
    'Post': {
        'author': 'author',
    },
    'socialLink': {
        'author': 'author',
    },
    'author': {
        'socialLink': 'socialLink',
        'tokens': 'Token',
        'posts': 'Post',
    },
    'Token': {
        'user': 'author',
    },
}

# fmt: on